compile = g++ -std=c++20 -o

matprod: Mat_prod.cpp
	$(compile) matprod Mat_prod.cpp

part_2: server check

server: Server.cpp
	$(compile) server Server.cpp

check: Check.cpp
	$(compile) check Check.cpp
